name: Ask Junie To Review PR

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  ask-junie-review:
    runs-on: ubuntu-latest
    steps:
      - name: Post review request comment for Junie
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const body = `@jetbrains-junie Can you review this PR and provide feedback?\n\nTitle: ${pr.title}\nPR: #${prNumber} (${pr.html_url})`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });
