name: Docusaurus Site

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: site/package-lock.json

    - name: Install dependencies
      working-directory: ./site
      run: npm install

    - name: Build Docusaurus site
      working-directory: ./site
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: GCP auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker europe-docker.pkg.dev

    - name: Build and push Docker image
      working-directory: ./site
      run: |
        docker buildx build --platform linux/amd64 --push -t europe-docker.pkg.dev/aigentic-458115/aigentic-docker/aigentic-docs .

    - name: Deploy to Google Cloud Run
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud run deploy aigentic-docs \
          --image=europe-docker.pkg.dev/aigentic-458115/aigentic-docker/aigentic-docs \
          --project=aigentic-458115 \
          --region=europe-west4 \
          --platform=managed \
          --allow-unauthenticated \
          --ingress=all

